language: minimal
services: docker

env:
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="lunar"
    - ROS_DISTRO="melodic"

script:
  - docker run --rm -it -v `pwd`:/root/catkin_ws/src/ -w /root/catkin_ws ros:${ROS_DISTRO}-ros-core catkin_make_isolated
